baseURL = "https://herijooj.github.io/"
languageCode = "en"
title = "Heric's Site"
theme = "notepad"
enableRobotsTXT = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

relativeURLs = false
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  author = "Heric Camargo"

[languages]

  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
    title = "Heric's Site"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 10

      [[languages.en.menu.main]]
        name = "Photos"
        url = "/photos/"
        weight = 20

      [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        weight = 30

      [[languages.en.menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 40

      [[languages.en.menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 50

      [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 60

  [languages.pt-br]
    languageCode = "pt-br"
    languageName = "PortuguÃªs"
    weight = 2
    title = "Site do Heric"

    [languages.pt-br.menu]
      [[languages.pt-br.menu.main]]
        name = "Casa"
        url = "/"
        weight = 10

      [[languages.pt-br.menu.main]]
        name = "Fotos"
        url = "/photos/"
        weight = 20

      [[languages.pt-br.menu.main]]
        name = "Sobre"
        url = "/about/"
        weight = 30

      [[languages.pt-br.menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 40

      [[languages.pt-br.menu.main]]
        name = "Projetos"
        url = "/projects/"
        weight = 50

      [[languages.pt-br.menu.main]]
        name = "Contato"
        url = "/contact/"
        weight = 60
